# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 折影轻梦
subtitle: 小雏菊
description: 崇尚自由、热爱科学与艺术
keywords: 折影轻梦,Mixcm,轻惋,奈西萌,觅漫者
tags: PHP,Golang,Vue,Hexo,Typecho,WordPress,Javascript,Jquery,Bootstrap,Css,Element,Swoole,Nuxt,Apache,Nginx,Vuetify,CodeIgniter,Docker,Github.com,Photoshop,MySQL,Redis,睡眠,社会,功能,创意,设计,模板,博客,指南,自学,生命,交互,方案,人文,浪漫,唯心,音乐,古典
author: 折影轻梦
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://nexmoe.com/
root: /
permalink: :abbrlink.html
permalink_defaults:
language: zh-CN

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  auto_detect: false
  line_number: true
  tab_replace: '  '
  hljs: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 0

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-yet-the-books

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:nexmoe/nexmoe.github.io.git
  branch: master
- type: baidu_url_submitter ## 这是新加的

nofollow:
	enable: true
  exclude:
    - chainwon.com
    - nexmoe.com
    - mixcm.com

baidu_url_submit:
  count: 1 ## 提交最新的一个链接
  host: nexmoe.com ## 在百度站长平台中注册的域名
  token: 7q4YIgtzCuMdGNce ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

feed:
  type: atom
  path: atom.xml
  limit: 20
  content: true
  order_by: -date
  
aplayer:
  meting: true

sitemap:
  path: sitemap.xml
